version: '3.0'  
services:
  go-app:
    build:
      context: "./apps/go-app/"
      dockerfile: Dockerfile
    container_name: "go-app-${PROJECT_NAME}"
    volumes:
      - ./apps/go-app:/app
    ports:
      - 8000:8000
  zipkin:
    image: openzipkin/zipkin
    container_name: "zipkin-${PROJECT_NAME}"
    ports:
      - 9411:9411
  mongodb:
    hostname: "mongo-${PROJECT_NAME}"
    container_name: "mongo-${PROJECT_NAME}"
    image: "mongo:4"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"
#node-service
