version: '3.0'  
services:
  go-app:
    build:
      context: "./apps/go-app/"
      dockerfile: Dockerfile
    container_name: "go-app-${PROJECT_NAME}"
    volumes:
      - ./apps/go-app:/app
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - local-network
#node-service
  mongodb:
    hostname: "mongo-${PROJECT_NAME}"
    container_name: "mongo-${PROJECT_NAME}"
    image: "mongo:4"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"    
    networks:
      - local-network
  zipkin:
    image: openzipkin/zipkin
    container_name: "zipkin-${PROJECT_NAME}"
    ports:
      - 9411:9411
    networks:
      - local-network
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: "jaeger-${PROJECT_NAME}"
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - local-network
networks:
  local-network: