version: "3"

dotenv: [ ".env" ]

tasks:
  run:
    desc: "Executa o projeto"
    cmds: 
      - "docker-compose up --build -d"
  stop:
    desc: "Parar o projeto"
    cmds:
      - "docker-compose down"
    